# WARNING Some settings require nightly fmt.
# Execute with:
#     cargo +nighthly fmt

unstable_features = true
max_width = 120
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 2
enum_discrim_align_threshold = 32
struct_field_align_threshold = 32
fn_single_line = false
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
indent_style = "Visual"
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_doc_attributes = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
chain_width = 60
group_imports = "StdExternalCrate"
color = "Always"
condense_wildcard_suffixes = true